name: Generate CV

on:
  push:
    paths:
      - 'job_request.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended
        
    - name: Install Python dependencies
      run: |
        pip install openai
        
    - name: Run CV Generator
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python generate_cv.py
      
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-cv
        path: output.pdf
        
    - name: Commit result
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f output.pdf || true
        git commit -m "Add generated CV" || true
        git push || true
