name: Generate CV

on:
  workflow_dispatch:
    inputs:
      job_description:
        description: 'Job Description'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended
        
    - name: Install Python dependencies
      run: |
        pip install openai
    
    - name: Create job description file
      run: |
        echo "${{ github.event.inputs.job_description }}" > job_request.txt
        
    - name: Run CV Generator
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python generate_cv.py
      
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-cv-${{ github.run_number }}
        path: output.pdf
